ajout de la classe des tests unitaires de la classe Api en frontend
MasterDID2022/projet-s2 pull request #51
Opened 2023-05-12 13:01 UTC by rawi124

## Pull Request pour l'issue #49

#### Avancement

- [ ] Test

2023-05-12 18:10 UTC, Desmondmies approved these changes

2023-05-12 18:15 UTC, Desmondmies approved these changes
looks good to me again

2023-05-12 21:10 UTC, anastygnome requested changes
Il faudrait mettre à jour la ligne 

```xml 
        <sonar.coverage.exclusions>src/main/java/fr/univtln/m1infodid/projet_s2</sonar.coverage.exclusions>
        ```

pour que sonar n'ignore pas vos tests (on ignore le code javafx car pas testable en l'état.)

2023-05-12 21:10 UTC, anastygnome commented on frontend/pom.xml
> +
Hmm, vraiment?

2023-05-13 15:41 UTC, anastygnome approved these changes

2023-05-13 15:45 UTC, merged