Corrige les tests de l'annotation
MasterDID2022/projet-s2 pull request #53
Opened 2023-05-12 20:10 UTC by anastygnome

## Pull Request pour l'issue #52
Un souci se produisait lors de la persistance des annotations dans #48 qui provoquait l'échec des tests. 
Ceci est corrigé dans cette PR. 

fixes #52

2023-05-12 20:19 UTC, Theo-Hafsaoui requested changes, later dismissed

2023-05-12 20:19 UTC, Theo-Hafsaoui commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/DAO/AnnotationDAO.java
> +        try {
cf C.I
```
Use try-with-resources or close this "EpigrapheDAO" in a "finally" clause.
```

2023-05-12 20:32 UTC, anastygnome commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/DAO/AnnotationDAO.java
> +        try {
Surtout pas. Comme on utilise celui d'annotation DAO, l'entity manager est fermé au moment où celui de l'annotation l'est.

2023-05-13 07:25 UTC, khebtani-dorsaf approved these changes

2023-05-13 11:20 UTC, Theo-Hafsaoui approved these changes

2023-05-13 11:21 UTC, merged