recuperer les utilisateurs de BD dans le backend grace au dao
MasterDID2022/projet-s2 pull request #87
Opened 2023-05-18 18:41 UTC by rawi124

## Pull Request pour l'issue #86 

#### Avancement

- [ ] Implantation
- [ ] Test

2023-05-19 19:41 UTC, rawi124 commented
Pour tester, il faut mvn clean et compile et relancer docker ... 
dans App ajouter la ligne : log.info(Facade.afficherUtilisateurs().toString()); 
 un message dans le log devrait s afficher : [main] INFO fr.univtln.m1infodid.projet_s2.frontend.App - [{"id": "1", "email": "test@test.fr"}] qui représente les utilisateurs récupérés du backend vers le front, elle n est composé que d'un seul utilisateur puisque un seul a été ajoutée dans la base.

2023-05-19 19:48 UTC, 01022000 approved these changes

2023-05-19 20:22 UTC, Theo-Hafsaoui requested changes
Btw, il faut absolument squash vos commits et limiter le nombre de review a 2 team

2023-05-19 20:22 UTC, Theo-Hafsaoui commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/model/Utilisateur.java
> +    public String getMdp() {
Pas utile on utilise Lombok

2023-05-19 20:22 UTC, Theo-Hafsaoui commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/SI.java
> +		EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("EpiPU");
Code smell cf CI

2023-05-19 20:22 UTC, Theo-Hafsaoui commented on frontend/src/main/java/fr/univtln/m1infodid/projet_s2/frontend/server/Api.java
> +    public static List<Object> convertJsonToList(String jsonString) {
Pk un `Object` ? c'est pas pratique...

2023-05-19 20:22 UTC, Theo-Hafsaoui commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/SI.java
> +	public static String recupereUtilisateurs() {
a tester

2023-05-19 20:22 UTC, Theo-Hafsaoui commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/server/Lanceur.java
> +    public static void main(String[] args) throws JsonProcessingException {
pk ?

2023-05-19 20:32 UTC, rawi124 commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/SI.java
> +	public static String recupereUtilisateurs() {
tu veux dire ecrire ces tests unitaires ?

2023-05-19 20:33 UTC, Theo-Hafsaoui commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/SI.java
> +	public static String recupereUtilisateurs() {
oui

2023-05-19 20:41 UTC, Desmondmies requested changes

2023-05-19 20:41 UTC, Desmondmies commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/SI.java
> +			String resultat = "{\"id\": \"" + id + "\", \"email\": \"" + email + "\"}";
vaut mieux utiliser l'Object Mapper pour construire la chaine Json, comme dans l'Api, ça sera plus pratique par la suite

2023-05-19 20:41 UTC, Desmondmies commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/server/Lanceur.java
> +import com.fasterxml.jackson.databind.ObjectMapper;
import automatique ? il y a peut être des imports inutiles attention, cf CI

2023-05-19 20:41 UTC, Desmondmies commented on frontend/src/main/java/fr/univtln/m1infodid/projet_s2/frontend/Facade.java
> +    }
allez-retours avec api étrange mais ok, par contre List<Object> peut poser des soucis, à voir

2023-05-19 21:50 UTC, rawi124 commented on frontend/src/main/java/fr/univtln/m1infodid/projet_s2/frontend/Facade.java
> +    }
String utilisateursString = Api.recupereContenuUtilisateurs();
        List<String> utilisateursList = Api.convertJsonToList(utilisateursString); ... c etait demandé dans l issue que le retour devrait etre une liste ? je ne comprends pas ce qui est etrange, j ai deux fonctions complementaires que j appelle dans la facade

2023-05-19 21:55 UTC, rawi124 commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/SI.java
> +			String resultat = "{\"id\": \"" + id + "\", \"email\": \"" + email + "\"}";
dans les lignes juste apres on l utilise :
 			ObjectMapper objectMapper = new ObjectMapper();
			return objectMapper.writeValueAsString(listUtilisateurs);
ces deux lignes justes pour faciliter l interpretation, sinon bcp de petits soucis apres ..

2023-05-20 07:32 UTC, Theo-Hafsaoui commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/SI.java
> +		EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("EpiPU");
https://sonarcloud.io/project/issues?resolved=false&types=BUG&branch=86-api-front-back-annotateurs&id=MasterDID2022_projet-s2&open=AYgwuUiV9NAB96UqIYuC

2023-05-20 07:37 UTC, Theo-Hafsaoui requested changes
Il faut squash

2023-05-20 07:37 UTC, Theo-Hafsaoui commented on backend/src/main/java/fr/univtln/m1infodid/projet_s2/backend/SI.java
> +		System.out.println("ccccccccccccccccccccccccccccccccc");
A supprimer

2023-05-20 09:29 UTC, Theo-Hafsaoui approved these changes

2023-05-20 12:19 UTC, Desmondmies approved these changes

2023-05-20 12:29 UTC, merged